---

- name: make ftp dir
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ ftp_dir }}"
    - "{{ ftp_dir }}/tls"

- name: copy qiime2.org certs
  copy:
    src: "{{ item.src }}"
    dest: {{ ftp_dir }}/tls/{{ item.dest }}
  with_items:
    - { src: "*.qiime2.org.chained.crt", dest: pure-ftpd.pem }
    - { src: "*.qiime2.org.key", dest: pure-ftpd.key }
    
- name: copy ftp server docker compose template
  template:
    src: "{{ item }}"
    dest: "{{ ftp_dir }}"
  with_items:
    - ftp_server.yml
    - Dockerfile

- name: start ftp containers
  become: True
  command: /usr/local/bin/docker-compose -f {{ ftp_dir }}/ftp_server.yml up --build -d
  register: dc
  changed_when: '"Creating ftp_server_1" in dc.stderr'
