---

- name: ufw open ports
  ufw:
    rule: allow
    state: enabled
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "21"  # TODO Remove when Busywork is decommissioned
    - "22"
    - "80"
    - "443"
    - "30000:30099"  # TODO Remove when Busywork is decommissioned
